service: oppo-mmt-ugc-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    AWS_REGION: ${env:AWS_REGION}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
